### ISSUE TITLE
关于原书101页中ParseHandlerByName.java的讲解

### ISSUE THREAD

**Issue by aaa448579123** [Advanced-SpringCloud/cloud-book#2]
作者您好！读到此章时发现一些问题，不知是否为个人理解的问题，如有时间，烦请解答一下
问题为：ParseHandlerByName.java源代码中对于contract.parseAndValidatateMetadata(key.type())的函数返回值为List<MethodMetadata>，但后面讲解时SpringMvcContract中此函数的返回值为MethodMetadata，并没有返回值为List<MethodMetadata>的函数，但在BaseContract中有返回值为List<MethodMetadata>的函数，不知此处是否并没有调用SpringMvcContract的函数，而是直接调用的BaseContract中的函数？

**Comment by ztelur** [comment]
你好，ParseHandlerByName调用的是BaseContract中的parseAndValidatateMetadata函数，在该函数中会调用MethodMetadata parseAndValidateMetadata(Class<?> targetType, Method method)函数，SpringMvcContract会override该函数。

**Comment by aaa448579123** [comment]
好的，谢谢您的解答，我再好好看一下

**Comment by aaa448579123** [comment]
好的，谢谢您的解答，我再好好看一下这部分内容
