### ISSUE TITLE
关于本书的一点吐槽

### ISSUE THREAD

**Issue by QwQyewen** [Advanced-SpringCloud/cloud-book#5]
作者在本书中跟我们埋了很多坑，根据案例很多情况下运行报错，12章12.1.5访问受限资源
授权码类型请求
书上写的是
http://localhost:8766/oauth/authorize?client_id=client&amp;response_type=code&amp;redirect_uri=http://localhost:8888/login
参数中回调地址写的是http://localhost:8888/login，然后你认证服务器AuthorizationServerConfig中配置的回调地址为 http://localhost:8888/
    @Override
    public void configure(ClientDetailsServiceConfigurer clients) throws Exception {
        clients.inMemory().withClient("client")
                .authorizedGrantTypes("authorization_code","password", "refresh_token")
                .scopes("all")
                .secret("secret")
                .redirectUris("http://localhost:8888/")
        ;
    }
请求中带的回调地址和你后台配置的都不一样，怎么可能正常访问到请求授权页面？？？
应该会报错
error="invalid_grant", error_description="Invalid redirect: http://localhost:8888/login does not match one of the registered values."
这种情况让我困扰了很久！！！！！

**Comment by CANGWU** [comment]
在Finchley.Release版本中，关于回调地址的匹配方式只要协议、域名、端口以及path的起始地址匹配即可，可以参考源码中DefaultRedirectResolver#redirectMatches方法
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/12051479/53944180-c8b74880-40f9-11e9-9d7a-d45c537467b3.png">
如果还有问题，可以继续探讨，谢谢
