### ISSUE TITLE
第四章eureka.instance.hostname配置问题

### ISSUE THREAD

**Issue by zhaojun0193** [Advanced-SpringCloud/cloud-book#6]
在书上p42-p43的配置中有eureka.instance.hostname=client的配置
我配了这个之后访问 /say  就会报java.net.UnknownHostException: client 这个错。
但是看到github源码里并没有这个配置。我把这个删了就正常了。这个是什么问题呢？

还有p44  2.服务间调用 那个地方 应该是调用8765这个端口吧 书上写的8762

**Comment by CANGWU** [comment]
这两部分是书中的错误，第一个是服务实例的hostname配置当前主机的主机名，默认为localhost，书中出现的client是我们当时调试留下的小错误，项目中已经去除；服务调用端口确实是8765，这个也是错误之一，我们已经发现但是暂时无法改正。由于我们编辑得匆忙，书中存在一些小问题(应该不会超过两位数)，但是只要足够细心，相信读者能够轻松甄别。感谢您的支持和提问，如有其他问题还请继续反馈，谢谢！

**Comment by zhaojun0193** [comment]
好的，非常感谢 ！
